// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.macfu.dfs.namenode.rpc.model;

public interface ChooseDataNodeFromReplicasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string datanode = 1;</code>
   */
  String getDatanode();
  /**
   * <code>optional string datanode = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatanodeBytes();
}
