// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.macfu.dfs.namenode.rpc.model;

/**
 * Protobuf type {@code com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse}
 */
public  final class ChooseDataNodeFromReplicasResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse)
    ChooseDataNodeFromReplicasResponseOrBuilder {
  // Use ChooseDataNodeFromReplicasResponse.newBuilder() to construct.
  private ChooseDataNodeFromReplicasResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChooseDataNodeFromReplicasResponse() {
    datanode_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ChooseDataNodeFromReplicasResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            datanode_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.macfu.dfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_macfu_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.macfu.dfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_macfu_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.class, com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.Builder.class);
  }

  public static final int DATANODE_FIELD_NUMBER = 1;
  private volatile Object datanode_;
  /**
   * <code>optional string datanode = 1;</code>
   */
  public String getDatanode() {
    Object ref = datanode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      datanode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string datanode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDatanodeBytes() {
    Object ref = datanode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      datanode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDatanodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, datanode_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDatanodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, datanode_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse)) {
      return super.equals(obj);
    }
    com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse other = (com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse) obj;

    boolean result = true;
    result = result && getDatanode()
        .equals(other.getDatanode());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + DATANODE_FIELD_NUMBER;
    hash = (53 * hash) + getDatanode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse)
      com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.macfu.dfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_macfu_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.macfu.dfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_macfu_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.class, com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.Builder.class);
    }

    // Construct using com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      datanode_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.macfu.dfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_macfu_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor;
    }

    public com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse getDefaultInstanceForType() {
      return com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.getDefaultInstance();
    }

    public com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse build() {
      com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse buildPartial() {
      com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse result = new com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse(this);
      result.datanode_ = datanode_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse) {
        return mergeFrom((com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse other) {
      if (other == com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse.getDefaultInstance()) return this;
      if (!other.getDatanode().isEmpty()) {
        datanode_ = other.datanode_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object datanode_ = "";
    /**
     * <code>optional string datanode = 1;</code>
     */
    public String getDatanode() {
      Object ref = datanode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        datanode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string datanode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDatanodeBytes() {
      Object ref = datanode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        datanode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string datanode = 1;</code>
     */
    public Builder setDatanode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datanode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string datanode = 1;</code>
     */
    public Builder clearDatanode() {
      
      datanode_ = getDefaultInstance().getDatanode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string datanode = 1;</code>
     */
    public Builder setDatanodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datanode_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse)
  }

  // @@protoc_insertion_point(class_scope:com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse)
  private static final com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse();
  }

  public static com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChooseDataNodeFromReplicasResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChooseDataNodeFromReplicasResponse>() {
    public ChooseDataNodeFromReplicasResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChooseDataNodeFromReplicasResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChooseDataNodeFromReplicasResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ChooseDataNodeFromReplicasResponse> getParserForType() {
    return PARSER;
  }

  public com.macfu.dfs.namenode.rpc.model.ChooseDataNodeFromReplicasResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

