// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.macfu.dfs.namenode.rpc.model;

public interface ChooseDataNodeFromReplicasRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.macfu.dfs.namenode.rpc.ChooseDataNodeFromReplicasRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string filename = 1;</code>
   */
  String getFilename();
  /**
   * <code>optional string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>optional string excludedDataNodeId = 2;</code>
   */
  String getExcludedDataNodeId();
  /**
   * <code>optional string excludedDataNodeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getExcludedDataNodeIdBytes();
}
